spring:
  application:
    name: product-microservice

  ## Config Server conection
  config:
#    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888} #para docker
    import: "optional:configserver:http://localhost:8888" #para local
